### PR TITLE
Groups extension

### PR DESCRIPTION
**Pull request by seblemaguer**
Hello,

is something like this fine on your side? I can update the README if you are fine with in this PR later.

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi Sébastien,

I haven't been working on my Emacs packages lately.  I'm planning to spend some time on them again soon, and I'll take care of this then.  Thanks for your patience.

**Comment by seblemaguer** [comment]
no worries :) We are all busy :D

**Comment by alphapapa** [comment]
FYI, I'd like to handle this similarly to how I do in `org-ql` with `org-ql-defpred`:

* A macro like `bufler-defpred` would define a grouping predicate.  It would define a function like `bufler--predicate-NAME`, and it would add its `macrolet` form to a variable like `bufler-predicates`.
* A function like `bufler-define-expand-groups` would define a function `bufler-expand-groups` which would splice in the predicate `macrolet` forms into the `cl-macrolet` form.
* Users would do something like `(setf bufler-groups (bufler-expand-groups ...))`.
* New groups could be added with `bufler-defpred`, which would also call `bufler-define-expand-groups` to redefine the expansion function to include the new predicate.

What do you think?  Thanks.

**Comment by seblemaguer** [comment]
I think it is cleaner to what I did :D I don't know if I will have the time to implement that in a near future but if I do I can start something.

**Comment by alphapapa** [comment]
It's okay, I don't expect you to do all that according to my plans.  :)  I added some notes here: https://github.com/alphapapa/bufler.el/blob/master/notes.org#project-bufler-defpred So I'll close this PR.  I appreciate your interest, anyway!

**Pull request closed without merging**
