### PR TITLE
Add: erc group

### PR DESCRIPTION
**Pull request by seblemaguer**
I use ERC and I think it may be useful to group the buffers by networks. Therefore, I added this group definition in bufler

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi Sébastien,

Thanks, this is a good example of adding an another auto-group.

However, I think we should avoid adding more conditional code for other packages.  It would probably be best if this were provided in a separate file that users could load, or even mentioned in documentation so users could copy the code into their own configs.

**Comment by seblemaguer** [comment]
Hello, 

I think the separate file is a good idea. I was actually thinking of starting to separate erc, projectile, ... into some kind of of `bufler-additionnal-group.el`. However, we should try to have `bufler-defgroups` more generic. I can't work on this but I just want to know before: what do you think about it?

**Comment by alphapapa** [comment]
> I think the separate file is a good idea. I was actually thinking of starting to separate erc, projectile, ... into some kind of of `bufler-additionnal-group.el`. 

Unfortunately, the way Emacs feature loading works means that it's not generally practical to have a single file for features that relate to multiple packages.

> However, we should try to have `bufler-defgroups` more generic. I can't work on this but I just want to know before: what do you think about it?

See https://github.com/alphapapa/bufler.el/blob/39e756a23196d12792a3af4a06ab024d8235ee19/bufler-group-tree.el#L182 and https://github.com/alphapapa/bufler.el/blob/master/notes.org#use-group-tree-defmacro

**Comment by seblemaguer** [comment]
> Unfortunately, the way Emacs feature loading works means that it's not generally practical to have a single file for features that relate to multiple packages.

Ok I see. Maybe, a wiki page like for hydra? Or do you have something else in mind?

> See
> 
> https://github.com/alphapapa/bufler.el/blob/39e756a23196d12792a3af4a06ab024d8235ee19/bufler-group-tree.el#L182
> and https://github.com/alphapapa/bufler.el/blob/master/notes.org#use-group-tree-defmacro

Ah sorry, I completely missed that

**Comment by alphapapa** [comment]
> Ok I see. Maybe, a wiki page like for hydra? Or do you have something else in mind?

For this purpose, I'm not generally fond of wikis where people tend to dump things of varying quality in random places.  I'd rather have something like an `examples.org` file where examples of extra code can be kept, and additions can be proposed as PRs, like I have for `org-ql`.

**Comment by seblemaguer** [comment]
oki doki. I have a look at `org-ql` and do a proper pull request.

Thanks a lot

**Pull request closed without merging**
